a) Всі завдання виконувати засобами бібліотеки numpy без використання циклів для звернення до елементів матриць, а також функцій map(), filter(), reduce().  
b) В комірках ноутбука повинна бути вказана постановка задачі. Для створення формул повинен бути використаний LaTex.  
с) Перевірку здійснити за допомогою функції numpy.allclose()  

<h2>1. Виконати набiр вправ (Варiант 3)</h2>
<p>Вправи: 1, 3, 6, 7, 8, 14, 16, 18, 19, 22</p>

In [1]:
import numpy as np

Вправа 1. Вводиться число n. Вивести масив разміра nхn, в якому по
діагоналі йдуть числа від 1 до n, а інші числа рівні 0

In [2]:
def task_1():
    n = int(input())
    print(np.diag(np.arange(1, n + 1)))

In [3]:
task_1()

 5


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Вправа 3. Вводяться 4 числа n, m, r, c. Вивести масив розміру n на m, в якому в кожному r -му рядку і в кожному c-му стовбчику стоять 0, а інші елементи дорівнюють 1.

In [4]:
def task_3():
    n = int(input())
    m = int(input())
    r = int(input())
    c = int(input())
    arr = np.ones((n, m))
    arr[::r] = 0
    arr[:, ::c] = 0
    print(arr)

In [5]:
task_3()

 6
 7
 2
 3


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0.]]


Вправа 6. З клавіатури вводиться масив. Замінити всі ненульові елементи на - 1.

In [28]:
def task_6():
    arr = np.array([int(i) for i in input().split()])
    arr[arr!=0] = -1
    print(arr)

In [7]:
task_6()

 3 4 0 9 7 0 6 0 4 0 3


[-1 -1  0 -1 -1  0 -1  0 -1  0 -1]


Вправа 7. З клавіатури вводиться масив. Замінити всі нульові елементи на -1.

In [8]:
def task_7():
    arr = np.array([int(i) for i in input().split()])
    arr[arr==0] = -1
    print(arr)

In [9]:
task_7()

 3 4 0 9 7 0 6 0 4 0 3


[ 3  4 -1  9  7 -1  6 -1  4 -1  3]


Вправа 8. З клавіатури вводиться масив. Підрахувати в ньому кількість нульових та ненульвих елементів.

In [10]:
def task_8():
    arr = np.array([int(i) for i in input().split()])
    print('Нулiв: {}'.format(np.count_nonzero(arr == 0)))
    print('Не нулiв: {}'.format(np.count_nonzero(arr != 0)))

In [11]:
task_8()

 3 4 0 9 8 2 4 0 8 4 0


Нулiв: 3
Не нулiв: 8


Вправа 14. Розмістити на полі 8х8 0 та одиниці в шахматному порядку, використовуючи функцію повторення (*).

In [12]:
def task_14():
    print(np.reshape((([0, 1] * 4 + [1, 0] * 4) * 4), (8, 8)))

In [13]:
task_14()

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Вправа 16. Заповнити парні стовбчики матриці розміром n х n одиницями, а непарні – нулями.

In [14]:
def task_16():
    n = int(input())
    arr = np.empty((n, n), dtype=np.int8)
    arr[:, ::2] = 0
    arr[:, 1::2] = 1
    print(arr)

In [15]:
task_16()

 6


[[0 1 0 1 0 1]
 [0 1 0 1 0 1]
 [0 1 0 1 0 1]
 [0 1 0 1 0 1]
 [0 1 0 1 0 1]
 [0 1 0 1 0 1]]


Вправа 18. Заповнити вектор значеннями від 0 до n. Замінити знаки для всіх значеннь, що менші за n/2 та більші за 3n/4 на протилежні

In [16]:
def task_18():
    n = int(input())
    arr = np.arange(n)
    arr[arr < n/2] *= -1
    arr[arr > 3*n/4] *= -1
    print(arr)

In [17]:
task_18()

 10


[ 0 -1 -2 -3 -4  5  6  7 -8 -9]


Вправа 19. Згенерувати вектор з n випадкових чисел в діапазоні від 0 до 99. Визначити кількість унікальних чисел в послідовності.

In [18]:
def task_19():
    n = int(input())
    arr = np.random.randint(0, 100, n)
    print("В послідовності", arr, '-', np.unique(arr).size, 'унікальних чисел')

In [19]:
task_19()

 30


В послідовності [97 30  7  5 66 32 36 41 21 74 60 83 55 80  6 83 15 42 22 84 35 86 89 86
  6 88 20 78 20 82] - 26 унікальних чисел


Вправа 22. Ввести числа n і m. Згенерувати матрицю n на n випадкових цілих елементів з діапазону [0, m]. Замінити всі максимальні елементи цієї матриці на протилежні за знаком.

In [20]:
def task_22():
    n = int(input())
    m = int(input())
    matr = np.random.randint(0, m+1, (n, m))
    print('Початковий вектор\n', matr)
    matr[matr == np.max(matr)] *= -1
    print('Змінений вектор\n', matr)

In [21]:
task_22()

 4
 5


Початковий вектор
 [[4 1 3 1 4]
 [1 3 5 0 2]
 [3 2 1 0 4]
 [5 5 0 4 3]]
Змінений вектор
 [[ 4  1  3  1  4]
 [ 1  3 -5  0  2]
 [ 3  2  1  0  4]
 [-5 -5  0  4  3]]


<h3>2. Розв’язати систему за допомогою формул Крамера і виконати перевірку за допомогою:</h3>
<p>a) матричного множення;</p>
<p>b) функції numpy.linalg.solve().</p>
$$\left\{\begin{array}{c}x_1+2x_2+3x_3+4x_4=5\\2x_1+x_2+2x_3+3x_4=1\\3x_1+2x_2+x_3+2x_4=1\\4x_1+3x_2+2x_3+x_4=-5\end{array}\right.$$

In [22]:
def solve_Cramer():
    slae = np.array([[1, 2, 3, 4, 5], [2, 1, 2, 3, 1], [3, 2, 1, 2, 1], [4, 3, 2, 1, -5]])
    det_0 = np.linalg.det(slae[:,:4])
    det_1 = np.linalg.det(np.concatenate((slae[:,4:5], slae[:,1:4]), axis=1))
    det_2 = np.linalg.det(np.concatenate((np.concatenate((slae[:, 0:1], slae[:,4:5]), axis=1), slae[:, 2:4]), axis=1))
    det_3 = np.linalg.det(np.concatenate((np.concatenate((slae[:, 0:2], slae[:,4:5]), axis=1), slae[:, 3:4]), axis=1))
    det_4 = np.linalg.det(np.concatenate((slae[:, :3], slae[:, 4:5]), axis=1))
    x1 = det_1 / det_0
    x2 = det_2 / det_0
    x3 = det_3 / det_0
    x4 = det_4 / det_0
    x = np.array([x1, x2, x3, x4])
    print('Рiшення системи:\nX =', x)
    print('Перевiрка матричним множенням (A * X) = :\n', np.dot(slae[:, :4], x))
    print('Перевiрка за допомогою функції linalg.solve():\n', np.linalg.solve(slae[:, :4], slae[:, 4:5]))

In [23]:
solve_Cramer()

Рiшення системи:
X = [-2.  2. -3.  3.]
Перевiрка матричним множенням (A * X) = :
 [ 5.  1.  1. -5.]
Перевiрка за допомогою функції linalg.solve():
 [[-2.]
 [ 2.]
 [-3.]
 [ 3.]]


<h3>3. Обчислити значення матричного виразу.</h3>
$$2\left(A-B\right)\left(A^2+B\right),\;A=\begin{pmatrix}5&1&7\\-10&-2&1\\0&1&2\end{pmatrix},\;B=\begin{pmatrix}2&4&1\\3&1&0\\7&2&1\end{pmatrix}$$

In [24]:
def solve_matrix_equation():
    a = np.array([[5, 1, 7], [-10, -2, 1], [0, 1, 2]])
    b = np.array([[2, 4, 1], [3, 1, 0], [7, 2, 1]])
    print('A =', a, '\nB =', b)
    print('2*(A - B)*(A**2 + B) =\n', 2*np.dot((a-b),(np.dot(a, a)+b)))

In [25]:
solve_matrix_equation()

A = [[  5   1   7]
 [-10  -2   1]
 [  0   1   2]] 
B = [[2 4 1]
 [3 1 0]
 [7 2 1]]
2*(A - B)*(A**2 + B) =
 [[ 228  132  798]
 [-286 -336 -894]
 [-190 -184 -562]]


<h4>4. Розв’язати рівняння за допомогою оберненої матриці і виконати перевірку за допомогою:</h4>
<p>a) матричного множення;</p>
<p>b) функції numpy.linalg.solve().</p>
$$\begin{pmatrix}4&-2&0\\1&1&2\\3&-2&0\end{pmatrix}\ast X=\begin{pmatrix}0&-2&6\\2&4&3\\0&-3&4\end{pmatrix}$$

In [26]:
def solve_matrix_equation_2():
    a = np.array([[4, -2, 0], [1, 1, 2], [3, -2, 0]])
    b = np.array([[0, -2, 6], [2, 4, 3], [0, -3, 4]])
    inv_a = np.linalg.inv(a)
    x = np.dot(inv_a, b)
    print('Рiшення рiвняння X =\n', x)
    print('Перевiрка матричним множенням A * X =\n', np.dot(a, x))
    print('Перевiрка за допомогою функції linalg.solve():\n', np.linalg.solve(a, b))

In [27]:
solve_matrix_equation_2()

Рiшення рiвняння X =
 [[0. 1. 2.]
 [0. 3. 1.]
 [1. 0. 0.]]
Перевiрка матричним множенням A * X =
 [[ 0. -2.  6.]
 [ 2.  4.  3.]
 [ 0. -3.  4.]]
Перевiрка за допомогою функції linalg.solve():
 [[0. 1. 2.]
 [0. 3. 1.]
 [1. 0. 0.]]
